"""Compatibility shim that re-exports config values from the primary settings module."""

import config

DB_HOST = config.DB_HOST
DB_PORT = config.DB_PORT
DB_NAME = config.DB_NAME
DB_USER = config.DB_USER
DB_PASS = config.DB_PASS

TELEMETRY_ENABLED = config.TELEMETRY_ENABLED
TELEMETRY_SAMPLE_RATE = config.TELEMETRY_SAMPLE_RATE
TELEMETRY_RETENTION_DAYS = config.TELEMETRY_RETENTION_DAYS
TELEMETRY_HASH_SALT = config.TELEMETRY_HASH_SALT
TELEMETRY_QUEUE_SIZE = config.TELEMETRY_QUEUE_SIZE

RACETIME_URL = config.RACETIME_URL
SENTRY_URL = config.SENTRY_URL
DEBUG = config.DEBUG
