"""add platform to sgl2020 tournament table

Revision ID: 003b151676a6
Revises: dc1326423a10
Create Date: 2020-10-31 23:25:32.529676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003b151676a6'
down_revision = 'dc1326423a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sgl2020_tournament', sa.Column('platform', sa.String(length=45, collation='utf8_bin'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sgl2020_tournament', 'platform')
    # ### end Alembic commands ###
