"""nick verification table

Revision ID: 093bf2bbaa8b
Revises: 1850aceae097
Create Date: 2021-05-12 00:53:43.519404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '093bf2bbaa8b'
down_revision = '1850aceae097'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nick_verification',
    sa.Column('key', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('discord_user_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    sa.UniqueConstraint('key')
    )
    op.drop_index('srl_nick_UNIQUE', table_name='srl_nick_verification')
    op.drop_index('verification_id_UNIQUE', table_name='srl_nick_verification')
    op.drop_table('srl_nick_verification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('srl_nick_verification',
    sa.Column('srl_nick', mysql.VARCHAR(collation='utf8_bin', length=45), nullable=False),
    sa.Column('key', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('discord_user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('srl_nick'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('verification_id_UNIQUE', 'srl_nick_verification', ['key'], unique=True)
    op.create_index('srl_nick_UNIQUE', 'srl_nick_verification', ['srl_nick'], unique=True)
    op.drop_table('nick_verification')
    # ### end Alembic commands ###
