"""add smz3 multiworld table

Revision ID: 175558ca8e3f
Revises: 6d55247ff699
Create Date: 2020-09-20 22:12:05.316496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '175558ca8e3f'
down_revision = '6d55247ff699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smz3_multiworld',
    sa.Column('message_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('owner_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('smz3_multiworld')
    # ### end Alembic commands ###
