"""remove gtbk game

Revision ID: 1850aceae097
Revises: de2ba0a9b704
Create Date: 2021-04-30 20:19:24.110363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1850aceae097'
down_revision = 'de2ba0a9b704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gtbk_whitelist')
    op.drop_index('guess_UNIQUE', table_name='gtbk_guesses')
    op.drop_table('gtbk_guesses')
    op.drop_table('gtbk_games')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gtbk_games',
    sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('channel', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('game_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('gtbk_guesses',
    sa.Column('guess_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('game_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('twitch_user', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('guess', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('score', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('guess_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('guess_UNIQUE', 'gtbk_guesses', ['game_id', 'twitch_user'], unique=True)
    op.create_table('gtbk_whitelist',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('channel', mysql.VARCHAR(collation='utf8_bin', length=200), nullable=True),
    sa.Column('twitch_user', mysql.VARCHAR(collation='utf8_bin', length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
