"""add bo3 table

Revision ID: 2068c0d0161f
Revises: 2627b14936e4
Create Date: 2020-11-07 13:11:02.972786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2068c0d0161f'
down_revision = '2627b14936e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sgl2020_tournament_bo3',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('episode_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('room_name', sa.String(length=100, collation='utf8_bin'), nullable=True),
    sa.Column('event', sa.String(length=45, collation='utf8_bin'), nullable=True),
    sa.Column('platform', sa.String(length=45, collation='utf8_bin'), nullable=True),
    sa.Column('permalink', sa.String(length=200, collation='utf8_bin'), nullable=True),
    sa.Column('seed', sa.String(length=200, collation='utf8_bin'), nullable=True),
    sa.Column('password', sa.String(length=200, collation='utf8_bin'), nullable=True),
    sa.Column('status', sa.String(length=45, collation='utf8_bin'), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sgl2020_tournament_bo3')
    # ### end Alembic commands ###
