"""add new patch_distribution table

Revision ID: 2627b14936e4
Revises: 003b151676a6
Create Date: 2020-11-01 20:55:30.811573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2627b14936e4'
down_revision = '003b151676a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patch_distribution',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('patch_id', sa.String(length=45, collation='utf8_bin'), nullable=True),
    sa.Column('game', sa.String(length=45, collation='utf8_bin'), nullable=True),
    sa.Column('used', mysql.TINYINT(display_width=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patch_distribution_patch_id'), 'patch_distribution', ['patch_id'], unique=False)
    op.create_index(op.f('ix_patch_distribution_used'), 'patch_distribution', ['used'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patch_distribution_used'), table_name='patch_distribution')
    op.drop_index(op.f('ix_patch_distribution_patch_id'), table_name='patch_distribution')
    op.drop_table('patch_distribution')
    # ### end Alembic commands ###
