"""remove scheduling_needs_message_id

Revision ID: 2d29235b9738
Revises: 693b55b454c1
Create Date: 2021-04-24 21:15:27.610582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d29235b9738'
down_revision = '693b55b454c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass
