"""add category and goal columns

Revision ID: 42b2fbdb0a9b
Revises: 76935f78f2b5
Create Date: 2021-04-06 21:09:49.910968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b2fbdb0a9b'
down_revision = '76935f78f2b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('category', sa.String(length=200), nullable=True))
    op.add_column('tournaments', sa.Column('goal', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'goal')
    op.drop_column('tournaments', 'category')
    # ### end Alembic commands ###
