"""add rtgg to srlnick table

Revision ID: 599d269adf7f
Revises: 45ae1e242fc8
Create Date: 2020-10-18 20:43:38.105095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599d269adf7f'
down_revision = '45ae1e242fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('srlnick', sa.Column('rtgg_id', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_srlnick_rtgg_id'), 'srlnick', ['rtgg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_srlnick_rtgg_id'), table_name='srlnick')
    op.drop_column('srlnick', 'rtgg_id')
    # ### end Alembic commands ###
