"""add server description

Revision ID: 5bb20df3f035
Revises: ffdd07363665
Create Date: 2020-08-21 21:40:14.688639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb20df3f035'
down_revision = 'ffdd07363665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discord_server_lists', sa.Column('server_description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discord_server_lists', 'server_description')
    # ### end Alembic commands ###
