"""add scheduling needs stuff

Revision ID: 693b55b454c1
Revises: 42b2fbdb0a9b
Create Date: 2021-04-24 21:08:54.142528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '693b55b454c1'
down_revision = '42b2fbdb0a9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('admin_roles', sa.String(length=4000), nullable=True))
    op.add_column('tournaments', sa.Column('commentator_roles', sa.String(length=4000), nullable=True))
    op.add_column('tournaments', sa.Column('mod_channel_id', mysql.BIGINT(display_width=20), nullable=True))
    op.add_column('tournaments', sa.Column('mod_roles', sa.String(length=4000), nullable=True))
    op.add_column('tournaments', sa.Column('scheduling_needs_channel_id', mysql.BIGINT(display_width=20), nullable=True))
    op.add_column('tournaments', sa.Column('tracker_roles', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'tracker_roles')
    op.drop_column('tournaments', 'scheduling_needs_channel_id')
    op.drop_column('tournaments', 'mod_roles')
    op.drop_column('tournaments', 'mod_channel_id')
    op.drop_column('tournaments', 'commentator_roles')
    op.drop_column('tournaments', 'admin_roles')
    # ### end Alembic commands ###
