"""server description should not be nullable

Revision ID: 6d55247ff699
Revises: 5bb20df3f035
Create Date: 2020-08-21 21:40:55.933981

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d55247ff699'
down_revision = '5bb20df3f035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discord_server_lists', 'server_description',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('discord_server_lists', 'server_description',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               nullable=True)
    # ### end Alembic commands ###
