"""expand content column

Revision ID: 6dd556a95d2b
Revises: 599d269adf7f
Create Date: 2020-10-19 18:21:14.384304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6dd556a95d2b'
down_revision = '599d269adf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitch_command_text', 'content',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=200),
               type_=sa.String(length=4000, collation='utf8_bin'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('twitch_command_text', 'content',
               existing_type=sa.String(length=4000, collation='utf8_bin'),
               type_=mysql.VARCHAR(collation='utf8_bin', length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
