"""add discord_servers

Revision ID: 7326328356e2
Revises: 0dcd48078999
Create Date: 2020-08-21 21:22:06.830054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7326328356e2'
down_revision = '0dcd48078999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_server_lists',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('invite_id', sa.String(length=45), nullable=False),
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discord_server_categories',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('guild_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('channel_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('category_title', sa.String(length=200), nullable=False),
    sa.Column('category_description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_generated_games_hash_id'), 'audit_generated_games', ['hash_id'], unique=False)
    op.drop_index('idx_audit_generated_games_hash_id', table_name='audit_generated_games')
    op.create_index(op.f('ix_audit_messages_message_id'), 'audit_messages', ['message_id'], unique=False)
    op.drop_index('idx_audit_messages_message_id', table_name='audit_messages')
    op.create_index(op.f('ix_srlnick_srl_nick'), 'srlnick', ['srl_nick'], unique=False)
    op.create_index(op.f('ix_srlnick_twitch_name'), 'srlnick', ['twitch_name'], unique=False)
    op.drop_index('idx_srlnick_srl_nick', table_name='srlnick')
    op.drop_index('idx_srlnick_twitch_name', table_name='srlnick')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_srlnick_twitch_name', 'srlnick', ['twitch_name'], unique=False)
    op.create_index('idx_srlnick_srl_nick', 'srlnick', ['srl_nick'], unique=False)
    op.drop_index(op.f('ix_srlnick_twitch_name'), table_name='srlnick')
    op.drop_index(op.f('ix_srlnick_srl_nick'), table_name='srlnick')
    op.create_index('idx_audit_messages_message_id', 'audit_messages', ['message_id'], unique=False)
    op.drop_index(op.f('ix_audit_messages_message_id'), table_name='audit_messages')
    op.create_index('idx_audit_generated_games_hash_id', 'audit_generated_games', ['hash_id'], unique=False)
    op.drop_index(op.f('ix_audit_generated_games_hash_id'), table_name='audit_generated_games')
    op.drop_table('t_discord_server_categories')
    op.drop_table('discord_server_lists')
    # ### end Alembic commands ###
