"""create sgdailies table

Revision ID: 76935f78f2b5
Revises: 243a52b2162f
Create Date: 2021-02-28 00:43:00.976296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76935f78f2b5'
down_revision = '243a52b2162f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sgdailies',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('slug', sa.String(length=45), nullable=True),
    sa.Column('guild_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('announce_channel', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('announce_message', mysql.VARCHAR(length=2000), nullable=False),
    sa.Column('racetime_category', sa.String(length=45), nullable=True),
    sa.Column('racetime_goal', sa.String(length=45), nullable=True),
    sa.Column('race_info', mysql.VARCHAR(length=2000), nullable=False),
    sa.Column('active', mysql.TINYINT(display_width=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sgdailies')
    # ### end Alembic commands ###
