"""add league playoffs table

Revision ID: ac7f3aaeb08a
Revises: b56f29ae30c3
Create Date: 2020-12-09 22:53:31.536962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac7f3aaeb08a'
down_revision = 'b56f29ae30c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_playoffs',
    sa.Column('episode_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('playoff_round', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('game_number', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('preset', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('submitted', mysql.TINYINT(display_width=1), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('episode_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_playoffs')
    # ### end Alembic commands ###
