"""empty message

Revision ID: bf14ce951d41
Revises: 
Create Date: 2020-08-08 05:19:27.532961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf14ce951d41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_generated_games',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('randomizer', sa.String(length=45), nullable=True),
    sa.Column('hash_id', sa.String(length=50), nullable=True),
    sa.Column('permalink', sa.String(length=2000), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('gentype', sa.String(length=45), nullable=True),
    sa.Column('genoption', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('customizer', mysql.INTEGER(display_width=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_generated_games_hash_id'), 'audit_generated_games', ['hash_id'], unique=False)
    op.create_table('audit_messages',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('guild_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('message_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('channel_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('message_date', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=4000, collation='utf8mb4_bin'), nullable=True),
    sa.Column('attachment', sa.String(length=2000, collation='utf8mb4_bin'), nullable=True),
    sa.Column('deleted', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_messages_message_id'), 'audit_messages', ['message_id'], unique=False)
    op.create_table('config',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('guild_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('parameter', sa.String(length=45, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('value', sa.String(length=45, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('hash', sa.String(length=45, collation='utf8_bin'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gtbk_games',
    sa.Column('game_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('channel', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('gtbk_guesses',
    sa.Column('guess_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('game_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('twitch_user', sa.String(length=200), nullable=True),
    sa.Column('guess', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('score', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('guess_id')
    )
    op.create_index('guess_UNIQUE', 'gtbk_guesses', ['game_id', 'twitch_user'], unique=True)
    op.create_table('gtbk_whitelist',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('channel', sa.String(length=200, collation='utf8_bin'), nullable=True),
    sa.Column('twitch_user', sa.String(length=200, collation='utf8_bin'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mention_counters',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('guild_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('role_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('counter', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), nullable=False),
    sa.Column('last_used', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id')
    )
    op.create_table('permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('guild_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('role_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('permission', sa.String(length=45, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction_group',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('guild_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('channel_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('message_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('name', sa.String(length=400, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('bot_managed', mysql.INTEGER(display_width=11), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_table('reaction_role',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('guild_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('reaction_group_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('role_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('name', sa.String(length=45, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('emoji', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.String(length=400, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('protect_mentions', mysql.TINYINT(display_width=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seed_presets',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('randomizer', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('customizer', mysql.TINYINT(display_width=4), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('spoiler_races',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('srl_id', sa.String(length=45, collation='utf8_bin'), nullable=False),
    sa.Column('spoiler_url', sa.String(length=255, collation='utf8_bin'), nullable=False),
    sa.Column('studytime', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('srl_id')
    )
    op.create_table('srl_nick_verification',
    sa.Column('srl_nick', sa.String(length=45, collation='utf8_bin'), nullable=False),
    sa.Column('key', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('discord_user_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('srl_nick'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('srl_nick')
    )
    op.create_table('srl_races',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('srl_id', sa.String(length=45), nullable=False),
    sa.Column('goal', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('message', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('srl_id')
    )
    op.create_table('srlnick',
    sa.Column('discord_user_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('srl_nick', sa.String(length=200), nullable=True),
    sa.Column('twitch_name', sa.String(length=200), nullable=True),
    sa.Column('srl_verified', mysql.BIT(length=1), nullable=True),
    sa.PrimaryKeyConstraint('discord_user_id')
    )
    op.create_index(op.f('ix_srlnick_srl_nick'), 'srlnick', ['srl_nick'], unique=False)
    op.create_index(op.f('ix_srlnick_twitch_name'), 'srlnick', ['twitch_name'], unique=False)
    op.create_table('tournament_results',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('srl_id', sa.String(length=45, collation='utf8_bin'), nullable=True),
    sa.Column('episode_id', sa.String(length=45, collation='utf8_bin'), nullable=True),
    sa.Column('permalink', sa.String(length=200, collation='utf8_bin'), nullable=True),
    sa.Column('spoiler', sa.String(length=200, collation='utf8_bin'), nullable=True),
    sa.Column('event', sa.String(length=45, collation='utf8_bin'), nullable=True),
    sa.Column('status', sa.String(length=45, collation='utf8_bin'), nullable=True),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('week', sa.String(length=45, collation='utf8_bin'), nullable=True),
    sa.Column('written_to_gsheet', mysql.TINYINT(display_width=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twitch_channels',
    sa.Column('channel', sa.String(length=200), nullable=False),
    sa.Column('group', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('channel')
    )
    op.create_table('twitch_command_text',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('channel', sa.String(length=200, collation='utf8_bin'), nullable=True),
    sa.Column('command', sa.String(length=45, collation='utf8_bin'), nullable=True),
    sa.Column('content', sa.String(length=200, collation='utf8_bin'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_twitch_command_text_channel_command', 'twitch_command_text', ['channel', 'command'], unique=True)
    op.create_table('voice_role',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('guild_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('voice_channel_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('role_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_role')
    op.drop_index('idx_twitch_command_text_channel_command', table_name='twitch_command_text')
    op.drop_table('twitch_command_text')
    op.drop_table('twitch_channels')
    op.drop_table('tournament_results')
    op.drop_index(op.f('ix_srlnick_twitch_name'), table_name='srlnick')
    op.drop_index(op.f('ix_srlnick_srl_nick'), table_name='srlnick')
    op.drop_table('srlnick')
    op.drop_table('srl_races')
    op.drop_table('srl_nick_verification')
    op.drop_table('spoiler_races')
    op.drop_table('seed_presets')
    op.drop_table('reaction_role')
    op.drop_table('reaction_group')
    op.drop_table('permissions')
    op.drop_table('mention_counters')
    op.drop_table('gtbk_whitelist')
    op.drop_index('guess_UNIQUE', table_name='gtbk_guesses')
    op.drop_table('gtbk_guesses')
    op.drop_table('gtbk_games')
    op.drop_table('daily')
    op.drop_table('config')
    op.drop_index(op.f('ix_audit_messages_message_id'), table_name='audit_messages')
    op.drop_table('audit_messages')
    op.drop_index(op.f('ix_audit_generated_games_hash_id'), table_name='audit_generated_games')
    op.drop_table('audit_generated_games')
    # ### end Alembic commands ###
