"""add password column

Revision ID: dc1326423a10
Revises: 2f29f98e533b
Create Date: 2020-10-26 19:18:10.806853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1326423a10'
down_revision = '2f29f98e533b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sgl2020_tournament', sa.Column('password', sa.String(length=200, collation='utf8_bin'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sgl2020_tournament', 'password')
    # ### end Alembic commands ###
