"""expand content column

Revision ID: ddebe7199a33
Revises: 599d269adf7f
Create Date: 2020-10-19 18:10:27.192458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddebe7199a33'
down_revision = '599d269adf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
