"""add language

Revision ID: de2ba0a9b704
Revises: b71aea760df1
Create Date: 2021-04-25 15:16:50.654227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2ba0a9b704'
down_revision = 'b71aea760df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('lang', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'lang')
    # ### end Alembic commands ###
