"""add started column for spoiler races

Revision ID: f09140697acb
Revises: 2068c0d0161f
Create Date: 2020-11-21 17:44:19.264587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09140697acb'
down_revision = '2068c0d0161f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
