"""add order column

Revision ID: ffdd07363665
Revises: 7326328356e2
Create Date: 2020-08-21 21:37:50.040572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffdd07363665'
down_revision = '7326328356e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discord_server_categories', sa.Column('order', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discord_server_categories', 'order')
    # ### end Alembic commands ###
