from .asynctournament import asynctournament_blueprint
from .presets import presets_blueprint
from .racetime import racetime_blueprint
from .ranked_choice import ranked_choice_blueprint
from .settingsgen import settingsgen_blueprint
from .sglive import sglive_blueprint
from .tournament import tournament_blueprint
from .triforcetexts import triforcetexts_blueprint
from .schedule import schedule_blueprint
from .user import user_blueprint